image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy

before_script:
  # Installer Docker Compose si nécessaire
  - apk add --no-cache py3-pip
  - pip3 install docker-compose

  # Installer l'API Kaggle
  - pip3 install kaggle

  # Configurer l'API Kaggle
  - mkdir -p /root/.kaggle
  - echo "$KAGGLE_JSON_CONTENT" > /root/.kaggle/kaggle.json
  - chmod 600 /root/.kaggle/kaggle.json

build_image:
  stage: build
  script:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker build -t "$DOCKER_USERNAME"/weather-classifier .
    - docker push "$DOCKER_USERNAME"/weather-classifier
  only:
    - main
