language: python
python:
  - "3.8"

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker build --build-arg KAGGLE_JSON_ENCODED="$KAGGLE_JSON_ENCODED" -t $DOCKER_USERNAME/weather-classifier .

deploy:
  provider: script
  script:
    - docker push $DOCKER_USERNAME/weather-classifier
  on:
    branch: main
