version: '3.8'

services:
  weather-classifier:
    image: weather-classifier
    container_name: weather-classifier
    volumes:
      - "./input_images:/input"
      - "./output_predictions:/output"
    command: >
      sh -c "python /app/predict.py --input_dir /input --output_dir /output"
